language: node_js
node_js:
- stable

before_deploy:
- npm run build:prod

deploy:
- provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  fqdn: https://draw.inker.fun
  on:
    branch: master
- provider: surge
  project: ./docs/
  domain: https://draws.surge.sh
  skip_cleanup: true
  on:
    branch: master
